name: Refresh Samples Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  run_script:
    name: Refresh all JSON files in the samples/fr/ directory
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v2'
        with:
          token: ${{ secrets.PUBLIC_REPO_GHA_PAT }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm i
      - run: npm start
      - run: npm run convert
      - uses: EndBug/add-and-commit@v9
        with:
          add: '*.json'
          push: true
          message: 'chore: 🤖 Automatically refreshed data samples'



    